### ISSUE TITLE
system_profile dies when transport channel is disconnected

### ISSUE THREAD

**Issue by julian7** [sensu-plugins/GIR#26]
One of my nodes is under heavy load, and sometimes it loses connection to RabbitMQ. It looks like this becomes an unrecoverable error inside system_profile extension:

```
{"timestamp":"2015-05-05T08:07:00.704467-0500","level":"warn","message":"reconnecting to transport"}
/etc/sensu/extensions/system_profile.rb:95:in `read': closed stream (IOError)
        from /etc/sensu/extensions/system_profile.rb:95:in `block (2 levels) in read_file'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `block in run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `times'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.2/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.2/bin/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:23:in `load'
        from /opt/sensu/bin/sensu-client:23:in `<main>'
```

I've enclosed the whole `File.open(...) {}` block in a `begin...rescue` block to see the next time why it tried to die.

**Comment by julian7** [comment]
After a few iterations I got the following error:

```
system_profile: Error reading /proc/loadavg: closed stream
```

and the modified `read_file` method looks like this:

``` ruby
      def read_file(file_path, chunk_size = nil)
        content = ''
        File.open(file_path, 'r') do |file|
          read_chunk = proc do
            begin
              content << file.read(chunk_size)
              # #YELLOW
              unless file.eof? # rubocop:disable UnlessElse
                EM.next_tick(read_chunk)
              else
                yield content
              end
            rescue IOError => e
              @logger.warn("system_profile: Error reading #{file_path}: #{e.to_s}")
            end
          end
          read_chunk.call
        end
      end
```

I've seen this as a [previous](https://github.com/sensu/sensu-community-plugins/issues/507) [reports](https://groups.google.com/forum/#!topic/sensu-users/R9_8IY-s_jg) too, but so far nothing has happened.

Some say it's because of `file_chunk_size`, but it looks like the issue can happen with a tiny file too. It also possible there is an unhandled exception in the run loop, but frankly I don't care. If there is an IO error, then I believe the script already handled the output.
